Feature/7 카카오 tts 음성 합성
AI-Meeting/XD-Frontend pull request #15
Opened 2022-05-23 01:17 UTC by silverbeen

2022-05-23 05:33 UTC, kimjimin4471 requested changes

2022-05-23 05:33 UTC, kimjimin4471 commented on components/myInterview/profileBox/ProfileBox.tsx
> +  console.log(myInterview?.data);
console 지워주세요

2022-05-23 05:33 UTC, kimjimin4471 commented on lib/api/common/index.ts
> +    // } else if (status === 407) {
주석..지워주세요...

2022-05-25 06:10 UTC, silverbeen commented on components/myInterview/profileBox/ProfileBox.tsx
> +  console.log(myInterview?.data);
수정 했습니다.

2022-05-25 06:10 UTC, silverbeen commented on lib/api/common/index.ts
> +    // } else if (status === 407) {
지웠어요..

2022-05-25 06:11 UTC, kimjimin4471 approved these changes

2022-05-25 06:11 UTC, merged